mindmap

root((Подсистема\<br/\>кадровых уведомлений\<br/\>1С:ЗУП))

НСИ

Организации

Подразделения

Должности

Сотрудники

Получатели уведомлений

 

Регистрация изменений

Документ "Кадровое изменение"

Проведение документа

Движения по регистрам

 

Уведомления

Шаблоны уведомлений

Правила определения получателей

Статусы отправки

 

Отчётность

Отчёт по кадровым изменениям

Отчёт по отправленным уведомлениям

Отчёт по ошибкам

 

Администрирование

Роли пользователей

Константы системы

Служебная обработка
